apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.example.yaml
  - postgres.yaml
  - neo4j.yaml
  - rabbitmq.yaml
  - graphql-api.yaml
  - audio-ai-service.yaml
  - analytics-service.yaml
  - frontend.yaml
  - ingress.yaml
